[package]
name = "filesha-rs"
version = "0.1.0"
authors = ["Nicolas Marier <software@nmarier.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
ring = "0.13.5"
base64 = "0.12.1"
lazy_static = "1.4.0"